# Generated by Django 4.0.4 on 2022-06-20 14:53

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('crimereports', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='crimereport',
            name='slug',
        ),
        migrations.AddField(
            model_name='crimereport',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
    ]
