# Generated by Django 4.0.4 on 2022-06-22 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crimereports', '0003_county_lostitem_mostwanted_suspiciousactivity_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='mostwanted',
            name='is_captured',
            field=models.BooleanField(default=False),
        ),
    ]
