# Generated by Django 4.0.4 on 2022-06-22 22:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crimereports', '0004_mostwanted_is_captured'),
    ]

    operations = [
        migrations.AlterField(
            model_name='county',
            name='slug',
            field=models.SlugField(blank=True, max_length=100, unique=True),
        ),
    ]
