# Generated by Django 4.0.4 on 2022-06-22 22:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('crimereports', '0005_alter_county_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lostitem',
            name='county',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='crimereports.county'),
        ),
        migrations.AlterField(
            model_name='mostwanted',
            name='county',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='crimereports.county'),
        ),
        migrations.AlterField(
            model_name='suspiciousactivity',
            name='county',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='crimereports.county'),
        ),
        migrations.AlterField(
            model_name='terrorism',
            name='county',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='crimereports.county'),
        ),
        migrations.AlterField(
            model_name='theftreport',
            name='county',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='crimereports.county'),
        ),
    ]
